export const apiRoutes = {
  login: 'auth/login',
  hero: 'slides',
  about: 'about',
  team: 'team',
  teamById: 'team/member',
  store: 'store',
  contact: 'contact',
  event: 'events',
  gallery: 'gallery',
  addGallery: 'gallery/add_photo',
  updateGallery: 'gallery/update_photo',
  deleteGallery: 'gallery/delete_photo',
  giving: 'giving/modes',
  givingOptions: 'giving/options',
  editgivingOptions: 'giving/save_giving_account',
  onlineAccount: 'online_accounts',
  user: 'user',
  subscribers: 'subscribers',
  members: 'members',
  accounts: 'bank_accounts',
  live: 'live',
  banks: 'banks',
  countries: 'countries',
  contact_message: 'contact_messages',
  subscribe: 'subscribe',
}
