name: Deploy to the Server

on:
  push:
    branches:
      - main  # Change to your default branch if necessary

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # - name: Install sshpass
    #   run: sudo apt-get install -y sshpass
    - name: Pull latest changes from GitHub
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@premium198.web-hosting.com -p21098 << 'EOF'
        cd /home/justxlid/public_html/src
        git pull https://${{ secrets.GH_ACCESS_TOKEN }}@github.com/princeak8/just-worship-frontend.git main
        EOF

    - name: Run post-deployment scripts
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@premium198.web-hosting.com -p21098 << 'EOF'
        cd /home/justxlid/public_html/src

        # Run npm install
        npm install

        # Run npm build
        npm run build
